baseURL = ""
languageCode = "en-us"
title = "My Little Stories"
#theme = "colorlib"
theme = "wellington"
paginate = 10
enableEmoji = true

disqusShortname = "siva-personal-blog"
googleAnalytics = "G-G3FX16QYJD"
enableRobotsTXT = true
preserveTaxonomyNames = true

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  author = "Siva"
  subtitle = "My little stories"
  description = "Life, Health, Family, Career"
  facebook = ""
  twitter = "sivalabs"
  googleplus = ""
  youtube = ""
  github = ""
  linkedin = ""

[social]
  twitter = "sivalabs"
